//    uniCenta oPOS  - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2011 uniCenta
//    http://www.unicenta.net/unicentaopos
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.
package com.openbravo.pos.inventory;

import java.awt.Component;
import java.util.UUID;
import com.openbravo.basic.BasicException;
import com.openbravo.data.user.DirtyManager;
import com.openbravo.data.user.EditorRecord;
import com.openbravo.format.Formats;
import com.openbravo.pos.forms.AppLocal;
import com.openbravo.pos.forms.DataLogicSales;
import com.openbravo.data.gui.ComboBoxValModel;
import java.util.List;

/**
 *
 * @author adrianromero
 */
public class LocationsView extends javax.swing.JPanel implements EditorRecord {

    // private DirtyManager m_Dirty = new DirtyManager();    
    private String m_sID;
    //TODO CLEAN UP TAX HANDLING
    private List taxes;
    private ComboBoxValModel taxparentmodel;

    /** Creates new form LocationsEditor */
    public LocationsView(DirtyManager dirty, DataLogicSales sls) throws BasicException {
        initComponents();

        m_jName.getDocument().addDocumentListener(dirty);
        m_jAddress.getDocument().addDocumentListener(dirty);
        taxes = sls.getTaxList().list();
        taxparentmodel = new ComboBoxValModel(taxes);
        localTaxList.setModel(taxparentmodel);
        localTaxList.addActionListener(dirty);
        writeValueEOF();
    }

    @Override
    public void writeValueEOF() {

        m_sID = null;
        m_jName.setText(null);
        m_jAddress.setText(null);

        m_jName.setEnabled(false);
        m_jAddress.setEnabled(false);
        taxparentmodel.setSelectedKey(null);
    }

    @Override
    public void writeValueInsert() {

        m_sID = UUID.randomUUID().toString();
        m_jName.setText(null);
        m_jAddress.setText(null);

        m_jName.setEnabled(true);
        m_jAddress.setEnabled(true);
    }

    @Override
    public void writeValueDelete(Object value) {

        Object[] location = (Object[]) value;
        m_sID = Formats.STRING.formatValue(location[0]);
        m_jName.setText(Formats.STRING.formatValue(location[1]));
        m_jAddress.setText(Formats.STRING.formatValue(location[2]));
        taxparentmodel.setSelectedKey(location[3]);

        localTaxList.setModel(taxparentmodel);
        m_jName.setEnabled(false);
        m_jAddress.setEnabled(false);
    }

    @Override
    public void writeValueEdit(Object value) {

        Object[] location = (Object[]) value;
        m_sID = Formats.STRING.formatValue(location[0]);
        m_jName.setText(Formats.STRING.formatValue(location[1]));
        m_jAddress.setText(Formats.STRING.formatValue(location[2]));
        taxparentmodel.setSelectedKey(location[3]);
        localTaxList.setModel(taxparentmodel);
        m_jName.setEnabled(true);
        m_jAddress.setEnabled(true);
    }

    @Override
    public Object createValue() throws BasicException {
        Object[] location = new Object[4];
        location[0] = m_sID;
        location[1] = m_jName.getText();
        location[2] = m_jAddress.getText();
        location[3] = taxparentmodel.getSelectedKey();
        return location;
    }

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public void refresh() {
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        m_jAddress = new javax.swing.JTextField();
        localTaxList = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setText(AppLocal.getIntString("label.locationname")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(20, 20, 80, 30);

        m_jName.setToolTipText("Enter a Unique Name For This Location");
        add(m_jName);
        m_jName.setBounds(100, 20, 260, 28);

        jLabel3.setText(AppLocal.getIntString("label.locationaddress")); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(20, 50, 80, 30);

        m_jAddress.setToolTipText("Enter the Address for this Location");
        add(m_jAddress);
        m_jAddress.setBounds(100, 50, 260, 28);

        localTaxList.setToolTipText("Select the local tax for this location");
        localTaxList.setName("localTaxList"); // NOI18N
        add(localTaxList);
        localTaxList.setBounds(100, 80, 260, 28);

        jLabel1.setText("Local Tax");
        add(jLabel1);
        jLabel1.setBounds(20, 80, 80, 30);
    }// </editor-fold>//GEN-END:initComponents
        private void m_jAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jAddressActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_m_jAddressActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox localTaxList;
    private javax.swing.JTextField m_jAddress;
    private javax.swing.JTextField m_jName;
    // End of variables declaration//GEN-END:variables
}
